// Communities + tools + showcase data
window.SGF_DATA = {
  communities: [
    {
      name: "GenHQ",
      url: "https://www.skool.com/genhq",
      color: "#22D3EE",
      bg: "linear-gradient(135deg, #030D1A 0%, #0D2137 50%, #0891B2 100%)",
      sub: "GenHQ · #1 Tech Community on Skool",
      img: "assets/communities/GenHQ - Creative AI Education.jpg",
      focus: "Full-stack creative AI — tools, business & clients",
      mastered: ["AI Ads End-to-End", "Sound Design", "Client Acquisition", "Studio Structure", "Storytelling & Pacing"],
    },
    {
      name: "AI Creative Club",
      url: "https://www.skool.com/creativeai",
      color: "#FF0066",
      bg: "linear-gradient(135deg, #1a0010 0%, #5C0030 50%, #8B0037 100%)",
      sub: "Creative AI · Community",
      img: "assets/communities/AI Creative Club.jpg",
      focus: "AI tools, workflows & automation systems",
      mastered: ["Creative AI Workflows", "Content at Scale", "Live Ad Production", "Automation Systems"],
    },
    {
      name: "RoboNuggets",
      url: "https://www.skool.com/robonuggets",
      color: "#F59E0B",
      bg: "linear-gradient(135deg, #0A0600 0%, #3D2000 50%, #7C4200 100%)",
      sub: "RoboNuggets · Top 0.01% Skool",
      img: "assets/communities/The RoboNuggets Community.jpg",
      focus: "AI agents — build, automate & earn",
      mastered: ["Agentic AI Systems", "AI Agent Automation", "Client Implementation", "70+ Courses & Templates"],
    },
    {
      name: "Imperium Academy™",
      url: "https://www.skool.com/academy",
      color: "#FFFFFF",
      bg: "linear-gradient(135deg, #030303 0%, #111111 50%, #1E1E1E 100%)",
      sub: "Imperium Academy™ · by Charlie Morgan",
      img: "assets/communities/Imperium Academy.jpg",
      focus: "Agency & coaching — path to financial freedom",
      mastered: ["Client Acquisition", "Sales Scripting", "High Ticket Offers", "Business Systems", "Appointment Booking"],
    },
    {
      name: "Creativos",
      url: "https://www.skool.com/creativos",
      color: "#FFD700",
      bg: "linear-gradient(135deg, #FF6B35 0%, #FF2DB4 50%, #B721FF 100%)",
      sub: "Creativos · by Martin Velarde",
      img: "assets/communities/Creativos.jpg",
      focus: "#1 Comunidad IA Creativa en Latam",
      mastered: ["Higgsfield · HeyGen · Weavy", "UGC Automation", "E-commerce Automation", "Filmmaking IA", "0 → 100K Seguidores"],
    },
    {
      name: "Braud Academy",
      url: "https://www.skool.com/braudacademy",
      color: "#FF4080",
      bg: "linear-gradient(135deg, #0a0014 0%, #1A0028 50%, #2D0A3E 100%)",
      sub: "BraudAcademy · IA Creativa",
      img: "assets/communities/BraudAcademy - IA Creativa.jpg",
      focus: "Virtual influencers, UGC & AI avatars",
      mastered: ["Virtual Influencers", "UGC Monetization", "AI Avatar Creation", "Character Consistency", "Expert Prompting"],
    },
    {
      name: "AI Video Creators",
      url: "https://www.skool.com/ai-video-creators",
      color: "#4FB3FF",
      bg: "linear-gradient(135deg, #04080F 0%, #0A1628 50%, #0A2463 100%)",
      sub: "AVCC · Video Creators",
      img: "assets/communities/AI Video Creators Community.jpg",
      focus: "Viral AI video creation & content automation",
      mastered: ["AI Video Production", "Script Writing for Reels", "Prompt Engineering", "AI Avatars", "Ad Campaigns Lab"],
    },
    {
      name: "AI Genesis Academy",
      url: "https://www.skool.com/ai-elysium-academy-8301",
      color: "#818CF8",
      bg: "linear-gradient(135deg, #080814 0%, #0D0D2B 50%, #2D1B69 100%)",
      sub: "AI Genesis · Academy",
      img: "assets/communities/AI Genesis Academy.jpg",
      focus: "Ad-ready AI visual creation from zero",
      mastered: ["Idea → Visual Workflows", "Ad Campaign Labs", "Expert Prompt Engineering", "Scroll-Stopping Ads"],
    },
  ],
  tools: [
    { name: "OpenAI", img: "assets/tools/open ai.jpg" },
    { name: "Midjourney", img: "assets/tools/midjourney.png" },
    { name: "Runway", img: "assets/tools/runway.png" },
    { name: "Kling AI", img: "assets/tools/kling ai.jpg" },
    { name: "Flux AI", img: "assets/tools/flux ai.png" },
    { name: "Higgsfield", img: "assets/tools/higgsfield.jpg" },
    { name: "ElevenLabs", img: "assets/tools/elevenlabs.png" },
    { name: "Luma AI", img: "assets/tools/luma AI.jpg" },
    { name: "Ideogram", img: "assets/tools/ideogram.png" },
    { name: "CapCut", img: "assets/tools/capcut.png" },
    { name: "Nano Banana 2", img: "assets/tools/nano banana 2.jpg" },
    { name: "Veo 3.1", img: "assets/tools/veo 3.1.png" },
    { name: "Weavy Figma", img: "assets/tools/weavy figma.png" },
    { name: "Freepik", img: "assets/tools/freepik.png" },
    { name: "RunningHub", img: "assets/tools/RunningHub.png" },
    { name: "Claude Code", img: "assets/tools/claude code.png" },
    { name: "Claude", img: "assets/tools/claude.jpg" },
    { name: "Manus AI", img: "assets/tools/manus ai.png" },
    { name: "Perplexity", img: "assets/tools/perplexity.png" },
    { name: "Grok", img: "assets/tools/grok.png" },
    { name: "Gemini Google", img: "assets/tools/gemini google.png" },
    { name: "Google Antigravity", img: "assets/tools/google antigravity.png" },
    { name: "Arcads", img: "assets/tools/arcads.png" },
    { name: "HeyGen", img: "assets/tools/hey gen.png" },
    { name: "Seedance 2.0", img: "assets/tools/seedance 2.0.png" },
    { name: "Dreamina", img: "assets/tools/dreamina.jpg" },
    { name: "Hailuo AI", img: "assets/tools/hailou ai.png" },
    { name: "Flow Google", img: "assets/tools/flow google.png" },
  ],
  nicheImages: {
    fashion:     ["assets/media/niches/n1-fashion-1.jpg","assets/media/niches/n1-fashion-2.jpg","assets/media/niches/n1-fashion-3.jpg","assets/media/niches/n1-fashion-4.jpg","assets/media/niches/n1-fashion-5.jpg"],
    beauty:      ["assets/media/niches/n2-beauty-1.jpg","assets/media/niches/n2-beauty-2.jpg","assets/media/niches/n2-beauty-3.jpg","assets/media/niches/n2-beauty-4.jpg"],
    supplements: ["assets/media/niches/n3-supl-1.jpg","assets/media/niches/n3-supl-2.jpg","assets/media/niches/n3-supl-3.jpg","assets/media/niches/n3-supl-4.jpg"],
    pets:        ["assets/media/niches/n4-pets-1.jpg","assets/media/niches/n4-pets-2.jpg","assets/media/niches/n4-pets-3.jpg"],
    gadgets:     ["assets/media/niches/n5-tech-1.jpg","assets/media/niches/n5-tech-2.jpg","assets/media/niches/n5-tech-3.jpg","assets/media/niches/n5-tech-4.jpg","assets/media/niches/n5-tech-5.jpg"],
    sku:         ["assets/media/niches/n6-sku-1.jpg","assets/media/niches/n6-sku-2.jpg","assets/media/niches/n6-sku-3.jpg","assets/media/niches/n6-sku-4.jpg","assets/media/niches/n6-sku-5.jpg","assets/media/niches/n6-sku-6.jpg"],
  },
  showcase: [
    { type:"video", src:"assets/media/showcase/v01.mp4",  t:"Fashion editorial",    f:"Moda · Lookbook IA",       ratio:"9/16" },
    { type:"video", src:"assets/media/showcase/v02.mp4",  t:"UGC lifestyle",         f:"Lifestyle · Performance",  ratio:"9/16" },
    { type:"video", src:"assets/media/showcase/v03.mp4",  t:"Creative campaign",     f:"DTC · Cinematic",          ratio:"9/16" },
    { type:"video", src:"assets/media/showcase/v04.mp4",  t:"Brand campaign",        f:"Ecommerce · Visual",       ratio:"9/16" },
    { type:"video", src:"assets/media/showcase/v05.mp4",  t:"Product narrative",     f:"Visual Commerce",          ratio:"9/16" },
    { type:"video", src:"assets/media/showcase/v09.mp4",  t:"Date night editorial",  f:"Apparel · Lifestyle",      ratio:"9/16" },
    { type:"video", src:"assets/media/showcase/v10.webm", t:"AI creative demo",      f:"Demo · Sistema IA",        ratio:"16/9" },
    { type:"video", src:"assets/media/showcase/v11.webm", t:"Case study",            f:"Performance · Results",    ratio:"16/9" },
    { type:"video", src:"assets/media/showcase/v06.mp4",  t:"Home & lifestyle",      f:"Home · Aspiracional",      ratio:"9/16" },
    { type:"video", src:"assets/media/showcase/v07.mp4",  t:"Food campaign",         f:"Events · Hero ad",         ratio:"9/16" },
    { type:"video", src:"assets/media/showcase/v08.mp4",  t:"Holiday campaign",      f:"Seasonal · Premium",       ratio:"9/16" },
    { type:"img",   src:"assets/media/showcase/s-art-1.jpg", t:"Digital art",        f:"AI Art · Editorial",       ratio:"4/5" },
    { type:"img",   src:"assets/media/showcase/s-art-2.jpg", t:"3D product render",  f:"Product · 3D",             ratio:"4/5" },
    { type:"img",   src:"assets/media/showcase/s-cine-1.jpg",t:"Power shot",         f:"DTC · Cinematic",          ratio:"4/5" },
    { type:"img",   src:"assets/media/showcase/s-cine-2.jpg",t:"Texture close-up",   f:"Skincare · Macro",         ratio:"4/5" },
    { type:"img",   src:"assets/media/showcase/s-cine-3.jpg",t:"Product detail",     f:"Beauty · Close-up",        ratio:"4/5" },
  ],
};
