const fs = require('fs');
let app = fs.readFileSync('c:\\Users\\Admin\\Downloads\\WEB 2.0\\app.jsx', 'utf-8');
const problemsStart = app.indexOf('const PROBLEMS_DATA = {');
const problemsEnd = app.indexOf('function ProblemsSection({ lang }) {');
const replacement = const PROBLEMS_DATA = {
  es: [
    { text: "No tienen suficientes creativos nuevos por semana.", p: 1 },
    { text: "Dependen de diseñadores, editores o creativos internos saturados.", p: 1 },
    { text: "La producción creativa es lenta.", p: 1 },
    { text: "Los shootings, modelos, locaciones y UGC real hacen que producir sea costoso.", p: 1 },
    { text: "El coste por pieza creativa es demasiado alto.", p: 1 },
    { text: "No tienen suficientes variaciones por anuncio.", p: 1 },
    { text: "No pueden producir múltiples versiones de un mismo concepto.", p: 1 },
    { text: "No tienen suficiente volumen para testear diferentes hooks.", p: 1 },
    { text: "No pueden testear múltiples ángulos creativos al mismo tiempo.", p: 1 },
    { text: "Los creativos se repiten demasiado.", p: 1 },
    { text: "Las campañas se quedan sin material fresco rápidamente.", p: 1 },
    { text: "No tienen backlog creativo preparado.", p: 1 },
    { text: "No pueden reaccionar rápido a tendencias, promos o cambios de mercado.", p: 1 },
    { text: "No escalan volumen creativo cuando una campaña empieza a crecer.", p: 1 },
    { text: "Tienen dificultad para producir UGC de forma constante.", p: 1 },
    { text: "Dependen demasiado de creadores externos o influencers.", p: 1 },
    { text: "Cada nueva campaña exige empezar producción casi desde cero.", p: 1 },
    { text: "No tienen suficiente B-roll, imágenes, hooks y assets auxiliares.", p: 1 },
    { text: "Les cuesta producir contenido visual para diferentes formatos y plataformas.", p: 1 },
    { text: "No pueden crear campañas visuales grandes sin gastar demasiado en producción tradicional.", p: 1 },
    { text: "No testean suficientes hipótesis creativas.", p: 2 },
    { text: "No saben qué ángulos funcionan mejor.", p: 2 },
    { text: "No tienen suficientes variantes para encontrar anuncios ganadores.", p: 2 },
    { text: "Los creativos se queman rápido por fatiga creativa.", p: 2 },
    { text: "No refrescan campañas a tiempo.", p: 2 },
    { text: "Toman decisiones creativas basadas en intuición, no en aprendizaje estructurado.", p: 2 },
    { text: "No tienen un sistema claro para aprender de cada lote creativo.", p: 2 },
    { text: "No documentan qué hooks funcionaron y cuáles fallaron.", p: 2 },
    { text: "No tienen memoria creativa por cliente o por marca.", p: 2 },
    { text: "No conectan los resultados de performance con las siguientes piezas creativas.", p: 2 },
    { text: "No tienen datos creativos organizados por ángulo, formato, hook, oferta o audiencia.", p: 2 },
    { text: "No saben qué mensajes deben repetir, mejorar o descartar.", p: 2 },
    { text: "No pueden iterar rápido después de ver métricas como CTR, CPC, CPA, ROAS o retención.", p: 2 },
    { text: "No tienen suficiente velocidad entre idea, producción, test y siguiente iteración.", p: 2 },
    { text: "No tienen una librería de ángulos ganadores reutilizable.", p: 2 },
    { text: "No saben diferenciar entre un problema de media buying, oferta, landing o creatividad.", p: 2 },
    { text: "No tienen sistema para priorizar qué creativos producir primero.", p: 2 },
    { text: "No pueden probar suficientes formatos: estáticos, UGC, B-roll, lifestyle, product shots, comparativas, demos, etc.", p: 2 },
    { text: "No tienen un proceso para combatir la fatiga creativa antes de que la campaña muera.", p: 2 },
    { text: "Les cuesta optimizar el rendimiento desde la creatividad, no solo desde la configuración de anuncios.", p: 2 },
    { text: "No quieren contratar más diseñadores, editores, creadores UGC o productores.", p: 3 },
    { text: "Gestionar freelancers les consume demasiado tiempo.", p: 3 },
    { text: "La calidad cambia demasiado según quién produzca la pieza.", p: 3 },
    { text: "No tienen procesos creativos claros ni repetibles.", p: 3 },
    { text: "Hay problemas de coordinación entre media buyers, creativos, editores y cliente final.", p: 3 },
    { text: "El equipo creativo interno está sobrecargado.", p: 3 },
    { text: "Hay retrasos constantes en entregas.", p: 3 },
    { text: "No tienen un sistema fuerte de control de calidad.", p: 3 },
    { text: "Se rompe la consistencia de marca cuando intentan producir más rápido.", p: 3 },
    { text: "No tienen un workflow replicable para producir, revisar y entregar creativos.", p: 3 },
    { text: "Los costes de producción son impredecibles.", p: 3 },
    { text: "Cada nuevo cliente o campaña aumenta el caos operativo.", p: 3 },
    { text: "No tienen una estructura clara de briefing, revisión, aprobación y entrega.", p: 3 },
    { text: "Pierden tiempo corrigiendo errores que deberían evitarse desde el sistema.", p: 3 },
    { text: "No tienen nomenclatura, organización ni librería clara de assets.", p: 3 },
    { text: "La comunicación con freelancers o proveedores genera demasiada fricción.", p: 3 },
    { text: "No tienen una capa externa confiable que se haga responsable del output creativo.", p: 3 },
    { text: "No pueden escalar producción sin perder control.", p: 3 },
    { text: "No tienen SOPs creativos que permitan repetir calidad.", p: 3 },
    { text: "No tienen un sistema que acumule aprendizaje y mejore con el tiempo.", p: 3 }
  ],
  en: [
    { text: "Not enough new creatives per week.", p: 1 },
    { text: "Dependent on overloaded internal designers or editors.", p: 1 },
    { text: "Creative production is slow.", p: 1 },
    { text: "Shoots, models, locations, and real UGC make production expensive.", p: 1 },
    { text: "Cost per creative piece is too high.", p: 1 },
    { text: "Not enough variations per ad.", p: 1 },
    { text: "Cannot produce multiple versions of the same concept.", p: 1 },
    { text: "Not enough volume to test different hooks.", p: 1 },
    { text: "Cannot test multiple creative angles at once.", p: 1 },
    { text: "Creatives repeat too much.", p: 1 },
    { text: "Campaigns run out of fresh material quickly.", p: 1 },
    { text: "No prepared creative backlog.", p: 1 },
    { text: "Cannot react quickly to trends, promos, or market changes.", p: 1 },
    { text: "Don't scale creative volume when a campaign starts growing.", p: 1 },
    { text: "Difficulty producing UGC consistently.", p: 1 },
    { text: "Rely too heavily on external creators or influencers.", p: 1 },
    { text: "Every new campaign requires starting production almost from scratch.", p: 1 },
    { text: "Not enough B-roll, images, hooks, and auxiliary assets.", p: 1 },
    { text: "Struggle to produce visual content for different formats and platforms.", p: 1 },
    { text: "Cannot create large visual campaigns without spending too much on traditional production.", p: 1 },
    { text: "Don't test enough creative hypotheses.", p: 2 },
    { text: "Don't know which angles work best.", p: 2 },
    { text: "Not enough variants to find winning ads.", p: 2 },
    { text: "Creatives burn out quickly due to ad fatigue.", p: 2 },
    { text: "Campaigns aren't refreshed on time.", p: 2 },
    { text: "Creative decisions are based on intuition, not structured learning.", p: 2 },
    { text: "No clear system to learn from each creative batch.", p: 2 },
    { text: "Don't document which hooks worked and which failed.", p: 2 },
    { text: "No creative memory per client or brand.", p: 2 },
    { text: "Performance results aren't connected to the next creative pieces.", p: 2 },
    { text: "No creative data organized by angle, format, hook, offer, or audience.", p: 2 },
    { text: "Don't know which messages to repeat, improve, or discard.", p: 2 },
    { text: "Cannot iterate quickly after seeing metrics like CTR, CPC, CPA, ROAS, or retention.", p: 2 },
    { text: "Not enough speed between idea, production, test, and next iteration.", p: 2 },
    { text: "No reusable library of winning angles.", p: 2 },
    { text: "Don't know how to differentiate between a media buying, offer, landing page, or creative problem.", p: 2 },
    { text: "No system to prioritize which creatives to produce first.", p: 2 },
    { text: "Cannot test enough formats: static, UGC, B-roll, lifestyle, product shots, comparisons, demos, etc.", p: 2 },
    { text: "No process to combat creative fatigue before the campaign dies.", p: 2 },
    { text: "Struggle to optimize performance through creatives, not just ad setup.", p: 2 },
    { text: "Don't want to hire more designers, editors, UGC creators, or producers.", p: 3 },
    { text: "Managing freelancers consumes too much time.", p: 3 },
    { text: "Quality varies too much depending on who produces the piece.", p: 3 },
    { text: "No clear or replicable creative processes.", p: 3 },
    { text: "Coordination issues between media buyers, creatives, editors, and the final client.", p: 3 },
    { text: "Internal creative team is overloaded.", p: 3 },
    { text: "Constant delays in deliveries.", p: 3 },
    { text: "No strong quality control system.", p: 3 },
    { text: "Brand consistency breaks when trying to produce faster.", p: 3 },
    { text: "No replicable workflow to produce, review, and deliver creatives.", p: 3 },
    { text: "Production costs are unpredictable.", p: 3 },
    { text: "Every new client or campaign increases operational chaos.", p: 3 },
    { text: "No clear structure for briefing, review, approval, and delivery.", p: 3 },
    { text: "Wasting time fixing errors that should be avoided by the system.", p: 3 },
    { text: "No clear naming convention, organization, or asset library.", p: 3 },
    { text: "Communication with freelancers or suppliers generates too much friction.", p: 3 },
    { text: "No reliable external layer to take responsibility for creative output.", p: 3 },
    { text: "Cannot scale production without losing control.", p: 3 },
    { text: "No creative SOPs to ensure repeatable quality.", p: 3 },
    { text: "No system that accumulates learning and improves over time.", p: 3 }
  ]
};

;
app = app.substring(0, problemsStart) + replacement + app.substring(problemsEnd);

app = app.replace(
  '<span className="problems-total-badge mono">35</span>',
  '<span className="problems-total-badge mono">60</span>'
);
app = app.replace(
  '35 variaciones del mismo dolor. El cuello de botella creativo es el problema',
  '60 variaciones del mismo dolor. El cuello de botella creativo es el problema'
);
app = app.replace(
  '35 variations of the same pain. The creative bottleneck is the most',
  '60 variations of the same pain. The creative bottleneck is the most'
);

fs.writeFileSync('c:\\Users\\Admin\\Downloads\\WEB 2.0\\app.jsx', app, 'utf-8');
console.log('app.jsx updated successfully');
