// Communities + tools + showcase data
window.SGF_DATA = {
  communities: [
    "AI Camp",
    "Arca Collective",
    "Creative AI Lab",
    "Prompt Engineers Guild",
    "Performance Creative Club",
    "DTC Operators",
    "AI Ad Creators",
    "Generative Media Society",
  ],
  tools: [
    "OpenAI",
    "Midjourney",
    "Runway",
    "Kling",
    "Flux",
    "Sora",
    "ComfyUI",
    "Higgsfield",
    "ElevenLabs",
    "Luma",
    "Ideogram",
    "CapCut",
    "Pika",
    "Stable Diffusion",
  ],
  showcase: [
    { t: "Fashion editorial", f: "Moda · Lookbook IA", ratio: "4/5" },
    { t: "UGC hyperreal", f: "Beauty · Before/After", ratio: "9/16" },
    { t: "Pet character", f: "Mascotas · Hero ad", ratio: "1/1" },
    { t: "Product scene", f: "Suplementos · Lifestyle", ratio: "4/5" },
    { t: "Impossible set", f: "DTC · Cinematic", ratio: "16/9" },
    { t: "Model swap", f: "Apparel · Variación", ratio: "4/5" },
    { t: "Texture close-up", f: "Skincare · Macro", ratio: "1/1" },
    { t: "Seasonal drop", f: "Fashion · Campaña", ratio: "9/16" },
  ],
};
